


PYTHON = python3
MAIN_FILE = main.py
PLAYER_ENTRY_FILE = player_entry.py


.PHONY: run_main
run_main:
	$(PYTHON) $(MAIN_FILE)



.PHONY: help
help:
	@echo "Usage: make [target]"
	@echo "Targets:"
	@echo "  run_main          : Run the main.py file"
	@echo "  run_player_entry  : Run the player_entry.py file"
	@echo "  run_all           : Run both main.py and player_entry.py"
	@echo "  help              : Show this help message"
