


PYTHON = python3
MAIN_FILE = main.py
PLAYER_ENTRY_FILE = player_entry.py


.PHONY: run_main
run_main:
	$(PYTHON) $(MAIN_FILE)

run_player_entry:
	$(PYTHON) $(PLAYER_ENTRY_FILE)


.PHONY: help
help:
	@echo "Usage: make [target]"
	@echo "Targets:"
	@echo "  run_main          : Run the main.py file"
	@echo "  run_player_entry  : Run the player_entry.py file"

